BCW-00007
Atevann/botec-web pull request #10
Opened 2024-02-28 05:41 UTC by Amrik97

2024-02-28 07:28 UTC, Atevann requested changes

2024-02-28 07:28 UTC, Atevann commented on app/Providers/Localization.php
> +class Localization
Это выглядит лишним, дублирует код из middleware

2024-02-28 07:28 UTC, Atevann commented on config/app.php
> +        'English' => 'en',
Можно сделать чтоб по дефолту локаль была ru (86 строка, параметр 'locale')

2024-02-28 07:28 UTC, Atevann commented on resources/lang/ru.json
> +{
Переводы должны быть в одном месте. У тебя они есть в /lang/ru/ и /resources/lang/ru

2024-02-28 07:28 UTC, Atevann commented on resources/views/layouts/navigation.blade.php
> +    <x-slot name="content">
Можешь воспользоваться тегом <x-dropdown-link">, он автоматически отправит запрос на указанную ссылку, например
`<x-dropdown-link href="language?lng=ru">RU</x-dropdown-link>`

Живой пример есть в кнопке перехода на страницу профиля:
```
<x-dropdown-link :href="route('profile.edit')">
    {{ __('Profile') }}
</x-dropdown-link>
```

2024-02-28 07:28 UTC, Atevann commented on resources/views/layouts/navigation.blade.php
> +    </form>
Нет открывающего тега формы. + она не нужна будет при использовании <x-dropdown-link>

2024-02-28 07:28 UTC, Atevann commented on resources/views/layouts/navigation.blade.php
> +    </form>
То же самое, непонятный тег закрывающий форму

2024-02-28 07:28 UTC, Atevann commented on routes/web.php
> +    $today = \Carbon\Carbon::now()
Непонятно что это и зачем

2024-02-28 07:28 UTC, Atevann commented on routes/web.php
> +        'date_message' => $dateMessage
В welcome шаблоне нет переменной date_message, так что впустую передаёшь его.

2024-02-28 07:28 UTC, Atevann commented on storage/framework/views/.gitignore
> -!.gitignore
А зачем gitignore удалил?
Теперь в эту директорию закоммитилась куча кэшей

2024-02-29 05:44 UTC, Atevann requested changes

2024-02-29 05:44 UTC, Atevann commented on resources/views/welcome.blade.php
> +                {{ __('Welcome to our website, :Name', ['name' => 'amanda']) }}
Кто такая аманда

2024-02-29 05:44 UTC, Atevann commented on resources/lang/ru.json
> +{
Перенести переводы в /lang/... или заюзать имеющиеся там

2024-02-29 05:44 UTC, Atevann commented on resources/views/layouts/navigation.blade.php
> +                        <x-dropdown-link href="http://127.0.0.1:8080/health">Status</x-dropdown-link>
health не надо добавлять для обычного пользователя. это системная инфа

2024-02-29 05:44 UTC, Atevann commented on resources/views/layouts/navigation.blade.php
> +                        <x-dropdown-link href="http://127.0.0.1:8080/dashboard">Dashboard</x-dropdown-link>
Если хочешь добавить дополнительные линки в навигацию, то надо заводить отдельный x-nav-link.
Но в задаче ничего не было сказано о добавлении новых элементов в блок навигации

2024-02-29 05:44 UTC, Atevann commented on resources/views/dashboard.blade.php
> +                {{ __('Welcome to our website, :Name', ['name' => 'amanda']) }}
Кто такая аманда???

2024-02-29 05:44 UTC, Atevann commented on resources/views/dashboard.blade.php
> -                    {{ __("You're logged in!") }}
Текст и содержание не меняем, в задаче сказано только локализовать проект

2024-02-29 05:44 UTC, Atevann commented on resources/views/partials/language_switcher.blade.php
> +<div class="flex justify-center pt-8 sm:justify-start sm:pt-0">
Рекомендую воспользоваться x-dropdown-link (см. коммент в navigation.blade.php

2024-02-29 05:44 UTC, Atevann commented on resources/views/status.blade.php
> +<x-app-layout>
Сервисную страницу не будем переводить

2024-02-29 11:40 UTC, Amrik97 commented on app/Providers/Localization.php
> +class Localization
done

2024-02-29 11:40 UTC, Amrik97 commented on resources/lang/ru.json
> +{
done

2024-02-29 11:40 UTC, Amrik97 commented on resources/views/layouts/navigation.blade.php
> +    <x-slot name="content">
done

2024-02-29 11:41 UTC, Amrik97 commented on resources/views/layouts/navigation.blade.php
> +    </form>
done

2024-02-29 11:41 UTC, Amrik97 commented on resources/views/layouts/navigation.blade.php
> +    </form>
done

2024-02-29 11:42 UTC, Amrik97 commented on routes/web.php
> +    $today = \Carbon\Carbon::now()
done

2024-02-29 11:42 UTC, Amrik97 commented on routes/web.php
> +        'date_message' => $dateMessage
done

2024-02-29 11:42 UTC, Amrik97 commented on storage/framework/views/.gitignore
> -!.gitignore
done

2024-02-29 11:42 UTC, Amrik97 commented on resources/views/welcome.blade.php
> +                {{ __('Welcome to our website, :Name', ['name' => 'amanda']) }}
done

2024-02-29 11:42 UTC, Amrik97 commented on resources/views/layouts/navigation.blade.php
> +                        <x-dropdown-link href="http://127.0.0.1:8080/health">Status</x-dropdown-link>
done

2024-02-29 11:43 UTC, Amrik97 commented on resources/views/layouts/navigation.blade.php
> +                        <x-dropdown-link href="http://127.0.0.1:8080/dashboard">Dashboard</x-dropdown-link>
done

2024-02-29 11:43 UTC, Amrik97 commented on resources/views/dashboard.blade.php
> +                {{ __('Welcome to our website, :Name', ['name' => 'amanda']) }}
done

2024-02-29 11:44 UTC, Amrik97 commented on resources/views/dashboard.blade.php
> -                    {{ __("You're logged in!") }}
done

2024-02-29 11:47 UTC, Amrik97 commented on resources/views/status.blade.php
> +<x-app-layout>
done

2024-02-29 12:51 UTC, Amrik97 commented on resources/views/partials/language_switcher.blade.php
> +<div class="flex justify-center pt-8 sm:justify-start sm:pt-0">
done

2024-03-01 05:39 UTC, Atevann requested changes

2024-03-01 05:39 UTC, Atevann commented on app/Http/Middleware/Localization.php
> +
strict types

2024-03-01 05:39 UTC, Atevann commented on app/Http/Middleware/Localization.php
> +    public function handle(Request $request, Closure $next)
Добавить возвращаемый тип

2024-03-01 05:39 UTC, Atevann commented on app/Http/Middleware/Localization.php
> +    * Handle an incoming request.
Актуализировать доку (перевести, более точно описать что это такое

2024-03-01 05:39 UTC, Atevann commented on app/Http/Middleware/Localization.php
> +class Localization
Добавить отступ перед классом и доку

2024-03-01 05:39 UTC, Atevann commented on app/Providers/AppServiceProvider.php
> +        view()->composer('partials.language_switcher', function ($view) {
Вынести код в отдельную protected функцию

2024-03-01 05:39 UTC, Atevann commented on lang/en/logins.php
> +    | Profile Reset Language Lines
Непонятная дока, да и в целом из названия файла не ясно за что отвечает этот словарь

2024-03-01 05:39 UTC, Atevann commented on lang/ru/logins.php
> +    | Profile Reset Language Lines
То же самое что и в en/logins.php

2024-03-01 05:39 UTC, Atevann commented on routes/web.php
> +Route::get('language/{locale}', function ($locale) {
Лучше добавить контроллер локализации и вынести логику из роутера в отдельный эндпоинт.
Так же рекомендую сделать маршрут '/language' и просто передавать в него GET- параметр необходимого языка, например, /language?lang=ru , и получать этот параметр в реквесте непосредственно в самом эндпоинте.
Таким образом ты сможешь избавиться от хардкода URL в шаблонах, добавив роуту название

2024-03-01 05:39 UTC, Atevann commented on resources/views/partials/language_switcher.blade.php
> +<div class="flex flex-col justify-center">
Лучше либо полностью вынести блок отображения языка в partials, либо в данном случае можно засунуть его в navigation без инклюдов. При этом если используешь x-dropdown, то код должен быть консистентный (так же как в других примерах)

2024-03-09 16:39 UTC, Atevann approved these changes

2024-03-09 16:40 UTC, merged